services:
  hallvoice:
    hostname: hallvoice
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.porte
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    volumes:
      - ./src:/hallvoice:ro
      - ./config:/hallvoice/config:ro
      - ./logs:/hallvoice/logs
      - ./mp3:/hallvoice/mp3:ro
      - ./custom:/hallvoice/custom:ro
    devices:
      - /dev/snd:/dev/snd
    networks:
      - default
  purge_api:
    hostname: purgeapi
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.API
    depends_on:
        - redis
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    volumes:
      - ./src:/hallvoice:ro
      - ./config:/hallvoice/config:ro
      - ./logs:/hallvoice/logs
    ports:
      - 8000:8000
    networks:
      - default
  redis:
    image: redis:latest
    hostname: redis
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./cache:/data
    networks:
      - default
networks:
  default:
